name: "proxy-chain-example"

services:
  reverse-proxy:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro